import { Agent, AgentConfig, Task, TaskResult, Message, MessageBus } from './types.js';
import { LLMProvider } from './llm/provider.js';

export abstract class BaseAgent implements Agent {
  config: AgentConfig;
  protected bus: MessageBus;
  protected inbox: Message[] = [];
  protected llmProvider: LLMProvider | null;

  constructor(config: AgentConfig, bus: MessageBus, llmProvider?: LLMProvider | null) {
    this.config = config;
    this.bus = bus;
    this.llmProvider = llmProvider ?? null;
    bus.subscribe(config.id, (msg) => this.receive(msg));
  }

  async receive(message: Message): Promise<void> {
    this.inbox.push(message);
    if (message.type === 'task') {
      const task = message.payload as Task;
      if (task._exec?.signal?.aborted) {
        this.bus.send({
          id: `result-${Date.now()}`,
          from: this.config.id,
          to: message.from,
          type: 'result',
          payload: this.createResult(task.id, 'failed', null, 'JOB_CANCELLED', { cancelReason: 'abort' }),
          timestamp: Date.now(),
        });
        return;
      }
      const result = await this.execute(task);
      this.bus.send({
        id: `result-${Date.now()}`,
        from: this.config.id,
        to: message.from,
        type: 'result',
        payload: result,
        timestamp: Date.now(),
      });
    }
  }

  abstract execute(task: Task): Promise<TaskResult>;

  /**
   * Try LLM execution with a structured prompt; fall back to the provided mock function
   * if no LLM provider is available or if the LLM call fails.
   */
  protected async llmOrMock<T>(
    task: Task,
    buildPrompt: () => { system: string; user: string },
    parseResponse: (content: string) => T,
    mockFn: (reason: string) => TaskResult
  ): Promise<TaskResult> {
    if (!this.llmProvider) {
      return mockFn('no LLM provider configured');
    }

    try {
      const { system, user } = buildPrompt();
      const llm = await this.llmProvider.askWithUsage(system, user, 0.7);
      const parsed = parseResponse(llm.content);
      return this.createResult(
        task.id,
        'success',
        {
          ...parsed,
          llmUsage: llm.usage,
          llmModel: llm.model,
          llmProvider: llm.provider,
        },
        `Generated by ${llm.provider}/${llm.model}`
      );
    } catch (err: any) {
      console.warn(`[${this.config.id}] LLM failed (${err.message}), falling back to mock`);
      return mockFn(`LLM error: ${err.message}`);
    }
  }

  protected createResult(
    taskId: string,
    status: TaskResult['status'],
    output: any,
    reasoning?: string,
    metadataExtra?: Record<string, unknown>
  ): TaskResult {
    return {
      taskId,
      agentId: this.config.id,
      status,
      output,
      reasoning,
      metadata: {
        executedAt: new Date().toISOString(),
        agentName: this.config.name,
        ...metadataExtra,
      },
    };
  }
}
