import { Agent, AgentConfig, Task, TaskResult, Message, MessageBus } from './types.js';
import { LLMProvider } from './llm/provider.js';

export abstract class BaseAgent implements Agent {
  config: AgentConfig;
  protected bus: MessageBus;
  protected inbox: Message[] = [];
  protected llmProvider: LLMProvider | null;

  constructor(config: AgentConfig, bus: MessageBus, llmProvider?: LLMProvider | null) {
    this.config = config;
    this.bus = bus;
    this.llmProvider = llmProvider ?? null;
    bus.subscribe(config.id, (msg) => this.receive(msg));
  }

  async receive(message: Message): Promise<void> {
    this.inbox.push(message);
    if (message.type === 'task') {
      const task = message.payload as Task;
      if (task._exec?.signal?.aborted) {
        this.bus.send({
          id: `result-${Date.now()}`,
          from: this.config.id,
          to: message.from,
          type: 'result',
          payload: this.createResult(task.id, 'failed', null, 'JOB_CANCELLED', { cancelReason: 'abort' }),
          timestamp: Date.now(),
        });
        return;
      }
      const result = await this.execute(task);
      this.bus.send({
        id: `result-${Date.now()}`,
        from: this.config.id,
        to: message.from,
        type: 'result',
        payload: result,
        timestamp: Date.now(),
      });
    }
  }

  abstract execute(task: Task): Promise<TaskResult>;

  /**
   * Execute a structured prompt. Mock output requires an explicitly selected mock provider.
   */
  protected async llmOrMock<T>(
    task: Task,
    buildPrompt: () => { system: string; user: string },
    parseResponse: (content: string) => T,
    resultStatus: (output: T) => TaskResult['status'] = () => 'success'
  ): Promise<TaskResult> {
    if (!this.llmProvider) {
      return this.createResult(task.id, 'failed', null, 'No LLM provider configured; select mock explicitly for a demo');
    }

    try {
      task._exec?.signal?.throwIfAborted();
      const { system, user } = buildPrompt();
      const llm = await this.llmProvider.askWithUsage(system, user, 0.7, task._exec?.signal);
      task._exec?.signal?.throwIfAborted();
      const raw = llm.content.trim();
      const json = raw.match(/```(?:json)?\s*([\s\S]*?)```/)?.[1] ?? raw;
      const object = JSON.parse(json);
      if (!object || typeof object !== 'object' || Array.isArray(object)) throw new Error('Expected a JSON object');
      const parsed = parseResponse(JSON.stringify(object));
      return this.createResult(
        task.id,
        resultStatus(parsed),
        {
          ...parsed,
          llmUsage: llm.usage,
          llmModel: llm.model,
          llmProvider: llm.provider,
          ...(llm.provider === 'mock' ? { generatedBy: 'mock' } : {}),
        },
        `Generated by ${llm.provider}/${llm.model}`
      );
    } catch (err) {
      const cancelled = task._exec?.signal?.aborted;
      return this.createResult(task.id, 'failed', null,
        cancelled ? 'JOB_CANCELLED' : `LLM error: ${err instanceof Error ? err.message : String(err)}`,
        cancelled ? { cancelReason: 'abort' } : undefined);
    }
  }

  protected createResult(
    taskId: string,
    status: TaskResult['status'],
    output: any,
    reasoning?: string,
    metadataExtra?: Record<string, unknown>
  ): TaskResult {
    return {
      taskId,
      agentId: this.config.id,
      status,
      output,
      reasoning,
      metadata: {
        executedAt: new Date().toISOString(),
        agentName: this.config.name,
        ...metadataExtra,
      },
    };
  }
}
